# Generated by Django 3.0.3 on 2020-03-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'name')},
        ),
    ]
