# Generated by Django 3.0.4 on 2020-03-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='usr_img',
        ),
    ]
