# Generated by Django 3.0.4 on 2020-03-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='song',
            new_name='songs',
        ),
    ]
