# Generated by Django 3.0.4 on 2020-03-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200309_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='songs',
            field=models.ManyToManyField(related_name='song', to='music.Song'),
        ),
    ]
