# Generated by Django 3.0.4 on 2020-03-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200309_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='songs',
            field=models.ManyToManyField(related_name='song', to='music.Songs'),
        ),
    ]
