# Generated by Django 3.0.4 on 2020-03-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_reviews_artist_reviews_reviews_song_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_type',
            field=models.CharField(choices=[('al', 'AL'), ('ar', 'AR'), ('so', 'SO'), ('pl', 'PL')], default='al', max_length=2),
        ),
    ]
